server:
  port: 8080

spring:
  application:
    name: meu-primeiro-springboot

  datasource:
    url: jdbc:postgresql://localhost:5432/meubanco
    username: usuario
    password: ${BANCO_SENHA}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true